SUPABASE_URL = "https://buikkhcsfyikfoyjrjuj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aWtraGNzZnlpa2ZveWpyanVqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDk0MzExOCwiZXhwIjoyMDk2NTE5MTE4fQ.hHvpR6Wxc8z_Xd-HZwOpy4noDwDNtoYslgYVIhoclFc"
GROQ_API_KEY = "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"
