SUPABASE_URL = "https://buikkhcsfyikfoyjrjuj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aWtraGNzZnlpa2ZveWpyanVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NDMxMTgsImV4cCI6MjA5NjUxOTExOH0.FVprBxKSTzFBzBKZNSVigQ5zYY1fD77Vgq8JGWkjSV0"
